import type { Course } from "@/types/course";

export const SAMPLE_COURSES: Course[] = [
  {
    id: "sample-sokcho-ocean",
    title: "속초 바다와 시장을 즐기는 하루",
    summary:
      "속초의 대표 해변과 전통시장을 함께 둘러보는 알찬 여행 코스입니다.",
    tags: ["바다", "시장", "먹거리"],
    estimatedStyle: "활기찬 도심·해안 여행",
    transportNote: "자동차 기준 장소 간 약 10~20분 이동",
    isPetFriendly: false,
    regionId: "sokcho",
    durationLabel: "당일 코스",
    recommendedReason:
      "바다 풍경과 속초의 대표 먹거리를 함께 즐기고 싶은 여행자에게 추천합니다.",
    mainImageUrl: "/images/regions/sokcho-card.jpg",
    places: [
      {
        id: "sokcho-beach",
        name: "속초해수욕장",
        category: "tour",
        address: "강원특별자치도 속초시 해오름로 190",
        tags: ["해변", "산책", "사진"],
        isPetFriendly: true,
        source: "sample",
      },
      {
        id: "sokcho-market",
        name: "속초관광수산시장",
        category: "food",
        address: "강원특별자치도 속초시 중앙로147번길 12",
        tags: ["시장", "먹거리", "맛집"],
        isPetFriendly: false,
        source: "sample",
      },
      {
        id: "cheongcho-lake",
        name: "청초호",
        category: "tour",
        address: "강원특별자치도 속초시 청초호반로",
        tags: ["호수", "산책", "야경"],
        isPetFriendly: true,
        source: "sample",
      },
    ],
  },
  {
    id: "sample-gangneung-coffee",
    title: "강릉 바다와 커피 감성 코스",
    summary:
      "안목해변의 바다 풍경과 강릉 커피거리를 여유롭게 즐기는 감성 여행입니다.",
    tags: ["커피", "오션뷰", "사진명소"],
    estimatedStyle: "여유로운 감성 여행",
    transportNote: "자동차 기준 전체 이동 약 35분",
    isPetFriendly: true,
    regionId: "gangneung",
    durationLabel: "반나절 코스",
    recommendedReason:
      "카페와 바다를 좋아하고 느긋한 여행을 원하는 사람에게 잘 어울립니다.",
    mainImageUrl: "/images/regions/gangneung-card.jpg",
    places: [
      {
        id: "anmok-beach",
        name: "안목해변",
        category: "tour",
        address: "강원특별자치도 강릉시 창해로14번길",
        tags: ["바다", "산책", "일출"],
        isPetFriendly: true,
        source: "sample",
      },
      {
        id: "gangneung-coffee-street",
        name: "강릉 커피거리",
        category: "food",
        address: "강원특별자치도 강릉시 창해로",
        tags: ["카페", "커피", "오션뷰"],
        isPetFriendly: true,
        source: "sample",
      },
      {
        id: "gyeongpo-lake",
        name: "경포호",
        category: "tour",
        address: "강원특별자치도 강릉시 저동",
        tags: ["호수", "자전거", "산책"],
        isPetFriendly: true,
        source: "sample",
      },
    ],
  },
  {
    id: "sample-yangyang-activity",
    title: "양양 서핑과 해변 액티비티 코스",
    summary:
      "양양의 대표 해변에서 서핑과 해안 풍경을 함께 즐기는 활동적인 코스입니다.",
    tags: ["서핑", "액티비티", "청년여행"],
    estimatedStyle: "활동적인 해양 여행",
    transportNote: "렌터카 또는 자동차 이용을 추천해요",
    isPetFriendly: false,
    regionId: "yangyang",
    durationLabel: "당일 코스",
    recommendedReason:
      "새로운 체험과 활동적인 여행을 선호하는 여행자에게 추천합니다.",
    mainImageUrl: "/images/regions/yangyang-card.jpg",
    places: [
      {
        id: "surfyy-beach",
        name: "서피비치",
        category: "leports",
        address: "강원특별자치도 양양군 현북면 하조대해안길",
        tags: ["서핑", "해변", "액티비티"],
        isPetFriendly: false,
        source: "sample",
      },
      {
        id: "jukdo-beach",
        name: "죽도해변",
        category: "tour",
        address: "강원특별자치도 양양군 현남면",
        tags: ["해변", "산책", "서핑"],
        isPetFriendly: true,
        source: "sample",
      },
      {
        id: "hajodae",
        name: "하조대",
        category: "tour",
        address: "강원특별자치도 양양군 현북면 하조대해안길",
        tags: ["전망", "일출", "사진"],
        isPetFriendly: true,
        source: "sample",
      },
    ],
  },
];